server:
  port: 8081

spring:
  application:
    name: demo
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  aop:
    proxy-target-class: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false


# redis分布式锁
redisson:
  address: redis://192.167.249.180:6379
  password: '123456'
  database: 5
  connectionPoolSize: 4
  connectionMinimumIdleSize: 4