server:
  port: 8081

spring:
  application:
    name: demo
  profiles:
    active: local
  datasource:
#    url: jdbc:mysql://localhost:3306/test
#    username: root
#    password: root
    url: jdbc:mysql://rm-2vcg431j388xlt5541o.mysql.cn-chengdu.rds.aliyuncs.com:3306/nearby_travel
    username: aliyun_test
    password: testRootZby!2020@
    driver-class-name: com.mysql.jdbc.Driver
  aop:
    proxy-target-class: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      FAIL_ON_EMPTY_BEANS: false
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false


# redis分布式锁
redisson:
#  address: redis://192.167.249.180:6379
  address: redis://localhost:6379
#  password: '123456'
  database: 0
  connectionPoolSize: 4
  connectionMinimumIdleSize: 4


# mq
lib:
  producer:
    accessKey: 1
    secretKey: 1
    nameSrvAddr: 192.167.249.180:9876
    groupId: demo-spring-boot
    sendMsgTimeoutMillis: 5000